### ISSUE TITLE
Missing space after ending periods in the UD2.5 training set

### ISSUE THREAD

**Issue by yuhaozhang** [UniversalDependencies/UD_Slovenian#1] opened 2020-02-17 08:44 UTC
In the latest UD 2.5 release, a large number of (if not all!) ending periods in the training conllu file (and thus the corresponding txt) seem to have been marked with "spaceAfter=no". This was not the case in previous versions. Is this an intentional fix or a mistake?

Meanwhile, the dev and test splits are consistent with previous versions.

**Comment by dan-zeman** [comment] 2020-02-17 11:11
Appeared in 2a7d278e1488e2a0f249f8073eac8df027a167f7

**Comment by kajad** [comment] 2020-02-17 20:21
Thanks for pointing out the issue. I don't think it's intentional, but I am reassigning this to @TomazErjavec, as this information comes from the initial ssj500k TEI XML conversion.

**Comment by TomazErjavec** [comment] 2020-02-17 21:50
This is definitely a bug, and it seems to be in all 3 files, not just in train.
I have no idea how this came about, as in my version of the complete ssj500k corpus this error is not there. However, from ssj500k to UD there are some many conversions, that it is hard to keep track.

I can't see myself right now taking the time for the detective work necessary to try and fix this in the conversion, but I can't see it being problematic to simply remove all SpaceAfter=no from the end of the sentences.

**Comment by yuhaozhang** [comment] 2020-02-17 21:56
Thanks for the prompt reponse! We can definitely do a simple fix on our side. My original intention was to bring this into the attention of the UD team so that it can be fixed in future releases.

Thanks for all the efforts!

**Comment by TomazErjavec** [comment] 2020-02-18 08:31
> My original intention was to bring this into the attention of the UD team so that it can be fixed in future releases.

And it's much appreciated, thank you! I will have a look at our data as soon as possible, but, yes, it will take a while to make it into the official release, so, for now, best if you patch the Slovenian data yourself. Thanks again.

**Comment by AngledLuffa** [comment] 2020-11-19 23:54
We switched our conversation scripts when rebuilding models for 2.7, I forgot to include the patch, and I wound up hitting the same issue a second time.  Any timeline for the fix making it into the official data?  Thanks!

**Comment by robvanderg** [comment] 2021-04-23 09:20
Is there a fix for 2.8?, otherwise it might make more sense to remove all "spaceAfter=no" in the last tokens?

**Comment by TomazErjavec** [comment] 2021-04-23 18:05
> otherwise it might make more sense to remove all "spaceAfter=no" in the last tokens?

Yes, I imagine this _is_ the fix; I applied it to the dev branch. 

As Dan pointed out, this bug comes from 429db2d, which, I just now noticed, was committed by @kajad, nice to know it wasn't my fault!

**Comment by kajad** [comment] 2021-04-24 08:28
I am reopening this issue until the cause of the issue is resolved with @TomazErjavec offline. In any case, the long-term solution should be that the segmentation in SSJ-UD remains identical to the original ssj500k corpus segmentation (http://hdl.handle.net/11356/1210).

**Comment by TomazErjavec** [comment] 2021-04-25 15:18
> cause of the issue is resolved 

Resolved, cf. https://github.com/clarinsi/jos2ud/.

**Closed as completed by TomazErjavec** 2021-04-25 15:18 UTC
Labels: bug
